"""
Django settings for RESCLIMA project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import json

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k2va29q6&j)hb4cb1q7jq(k(qtl(sr0!hcunjzp@wc6@mt8!ps'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
MESSAGE_LEVEL = 40
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.gis',
	'django.contrib.postgres',
	'layer',
	'search',
	'style',
	'vectorLayers',
	'rasterLayers',
	'timeSeries',
	'tms',
	'main',
	'simulation',
	'rest_framework',
	'easy_thumbnails',
	'dash',
	'dash.contrib.apps.public_dashboard',
	'dash.contrib.layouts.bootstrap2',
	'dash.contrib.plugins.dummy',
	'dash.contrib.plugins.image',
	'dash.contrib.plugins.memo',
	'dash.contrib.plugins.rss_feed',
	'dash.contrib.plugins.url',
	'dash.contrib.plugins.video',
	'dash.contrib.plugins.weather',
	'd3',
	#'producto_layout',
)

MIDDLEWARE_CLASSES = (
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	#'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'RESCLIMA.urls'
TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'RESCLIMA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# DB_PARAMS = "/home/carlos/Desktop/MateriaIntegradora/DATACITY/dbparams.json"
DB_PARAMS = "/home/fernando/Documentos/GIT/DATACITY/dbparams.json"

dbParams = None
with open(DB_PARAMS) as data_file:
		dbParams = json.load(data_file)
#print dbParams
DATABASES = {
	'default': {
		'ENGINE': 'django.contrib.gis.db.backends.postgis',
		'NAME': dbParams["dbname"],
		'USER':dbParams["user"],
		'PASSWORD':dbParams["password"],
		'HOST': dbParams["host"],
		'PORT':dbParams["port"]
	}
}
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Celery configuration
CELERY_BROKER_URL = 'amqp://resclima:resclima@localhost:5672/resclima'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'amqp://resclima:resclima@localhost:5672/resclima'
CELERY_RESULT_SERIALIZER = 'json'

# paths for user data
STYLE_FILES_PATH = "/home/fernando/Documentos/styles/"
RASTER_FILES_PATH = "/home/fernando/Documentos/rasters/"
TEMPORARY_FILES_PATH = "/home/fernando/Documentos/tmp/"

AUTH_USER_MODEL = 'main.User'
